### ISSUE TITLE
Where are all the semi colons ??

### ISSUE THREAD

**Issue by reecefenwick** [mvillis/measure-mate#133]
I don't think I've seen a single semi colon in your javascript!

At least its consistent..

**Comment by mvillis** [comment]
Decided to adopt http://standardjs.com.
[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)

No semi-colons is part of its [rule set](http://standardjs.com/#rules)

Standard Js has really nice in-editor support (I use atom) as well as easy to include in your gulp workflow (just a preset for gulp-eslint)
