### ISSUE TITLE
Upgrade to React 15

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#149]
https://facebook.github.io/react/blog/2016/04/07/react-v15.html

Looks like there could be a chance of zero breaking changes and a possible performance boost!

**Comment by rloomans** [comment]
The fly in the ointment at the moment is [react-loader](https://github.com/quickleft/react-loader): it's still pulling in react ^0.14.0. We'll have to wait until it gets updated.

**Comment by mvillis** [comment]
support for 15 is on the way:
https://github.com/quickleft/react-loader/pull/41

**Comment by rloomans** [comment]
done
