### ISSUE TITLE
assessment create does not handle new tags (only existing ones)

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#23]
When you create a new assessment, if you add new tags they are not handled.
Need to fix!

**Comment by mvillis** [comment]
Will be waiting for this to be finished before delivering this functionality https://github.com/JedWatson/react-select/pull/660

**Comment by rloomans** [comment]
@mvillis did you see [this comment](https://github.com/JedWatson/react-select/pull/660#issuecomment-169249033) with a workaround?

> mitani commented on 6 Jan
> This was a show stopper for us, but there is a workaround. For those of you that need allowCreate today - you can just use filterOptions and add an option {label: Add ${term}, value: term, create:true} and then you just process it in your onChange function where you look for create === true

**Comment by mvillis** [comment]
cool. will check it out.
fyi  the tag api does not support the creation of tags yet.

**Comment by rloomans** [comment]
@mvillis It seems to... [97ebd4e](https://github.com/mvillis/measure-mate/commit/97ebd4ed7faef4840ab22950818ce5c96298f54c)

**Comment by mvillis** [comment]
I was expecting to have to create an api to sort through the tag options sent through as part of a team / assessment, identify any that don't exist, create them then add them to whichever relationship wants them.
We could broker this on the javascript side.....

**Comment by rloomans** [comment]
Looking to use a different component, at least until the upstream PR is fixed and merged. 

Eg,
- https://github.com/prakhar1989/react-tags
- https://github.com/olahol/react-tagsinput
