### ISSUE TITLE
Expose the observation variable for each stored measurement

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#39]
Update the assessment form to include a spot where the person selecting a given rating for an attribute can supply a series of comments.

**Comment by mvillis** [comment]
A version has been merged which provides this feature.

As mentioned in #86 I'm not that happy with it and feel as though a bit of a rethink may be needed.
This however may been good enough for now.....

What do you think @rloomans @mjohno

**Comment by rloomans** [comment]
I don't like that the comment is not saved without a rating selected. 

I also don't like that the "Saved" text appears by default... It should only appear if the text has been changed, and it's been saved. 

## 

Robert Loomans

**Comment by mvillis** [comment]
agreed. will work on it.

**Comment by mvillis** [comment]
checkout the latest changes @rloomans . I think its vastly better. Still feels clumsy that comments are tied to a rating being selected but hey...will refactor eventually....
