### ISSUE TITLE
how about some javascript tests hey!?!

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#41]
Yeah.....so there are currently zero tests around the javascript of the application.

Python coverage is now in the high nineties. Javascript is getting pretty jealous!

**Comment by rloomans** [comment]
Some blogs to investigate for react testing:
- http://www.bebetterdeveloper.com/coding/getting-started-react-mocha.html
- https://github.com/jesstelford/react-testing-mocha-jsdom
- http://www.hammerlab.org/2015/02/14/testing-react-web-apps-with-mocha/
- https://facebook.github.io/jest/docs/tutorial-react.html

and for code coverage:
- http://www.hammerlab.org/2015/02/21/testing-react-web-apps-with-mocha-part-2/
  - Jest does have coverage support now (https://facebook.github.io/jest/#use-coverage-to-generate-a-code-coverage-report)
- https://github.com/nickmerwin/node-coveralls

**Comment by rloomans** [comment]
https://github.com/quickleft/react-loader has a fairly lightweight approach to testing... may be a good first stab

**Comment by rloomans** [comment]
We've got some, the coverage needs improvement, but this will do for now.
