### ISSUE TITLE
improve usability of assessment form

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#46]
Was thinking something like this:

![mock up](https://cloud.githubusercontent.com/assets/3509371/12115403/b6f1d9f8-b3fd-11e5-9e63-c7119ab08c13.jpg)

Leverage bootstrap left tabs:
https://react-bootstrap.github.io/components.html#left-tabs

any thoughts @rloomans @mjohno ?
## Work Left To Do
- [x] Replace scrolling view with tabs
- [x] Implement next/preview at the bottom of each attribute
- [x] Put controls around navigation to help with form validation and ensure you can't go beyond the first/last tab
- [x] clean up mobile view*\* this may be significant
- [x] add arrow to next button
- [x] visual indicator for the goodness of the rating

**Comment by rloomans** [comment]
We ran through this with CJ and we came up with something more like http://zots.net/bootstrap-slider/demo.html

(Please do _not_ look at the code... it's a brutal hack of the bootstrap slider example page)

**Comment by mvillis** [comment]
nice. Higher fidelity than my mockup!!!

From filing in previous assessments I think it is a good idea to be able to show all the different levels (including their detail) in a single view. Makes it easier to compare / contrast. 

Will put something together and we will adapt. 

UI design is fun!!!

**Comment by rloomans** [comment]
Another consideration for the LAMA is that we aren't just interested in the current measurement. In many teams a relatively low maturity in some attributes is acceptable in either the short, or even long, term. So, in addition to the current rating we need to record a target for each attribute. 

If you look again at http://zots.net/bootstrap-slider/demo.html you can see the direction we were thinking of taking it. 

## 

Robert Loomans

**Comment by mvillis** [comment]
Ok cool. Can you raise a separate feature request for storing a target measurement?

**Comment by mvillis** [comment]
Refactored the assessment form to use react-bootstrap (you'll see a lot less javascript looking code and more xml looking code as it's been replaced with JSX). Not sure if we want to roll this out across the board but was good to get my head around.

Had a crack at implementing the tabs view in a very very basic form:
https://measuremate.herokuapp.com/assessment-revised/34/

Needs a lot of work around mobile support, making it more obvious that you need to click through each one etc....

Not saying no to sliders....just having fun with tabs at the moment. Don't hesitate to commit your own changes and trial some stuff out for yourself.

**Comment by rloomans** [comment]
Maybe you just need to add a 'Next' button?

## 

Robert Loomans

**Comment by mvillis** [comment]
next button implemented. Have started a little to-do list on this card (see first comment). At the moment I haven't implemented any sliders as in the demo provided by @rloomans . Was thinking of revisiting this when we implement #52 

What do you think? What else needs to be done to close this card?

**Comment by mvillis** [comment]
With the addition of colour spines to ratings the UI tweaks are complete (outside of a couple of other issues in the backlog). Closing ticket. Nice work team!!
