### ISSUE TITLE
Add a target value for attributes

### ISSUE THREAD

**Issue by rloomans** [mvillis/measure-mate#52]
Along with the current ranking, record a target value for each attribute.

Work Breakdown:
- [x] add tests to the measurement api to support multiple ratings (as well as still support single ones)
- [x] update model to store multiple ratings for a given measurement
- [x] update model to include a rating type (ie. Current vs Target)
- [x] refactor existing app calls to work with the new multi-rating interface
- [x] update RatingList component to include a multi select. Intent is to be able to label a given rating as:
  - current
  - target
  - current / target
  - nothing
- [x] add validation to the form so the user know when they have finished making the right selections
- [x] hook the new component into the multiple-rating api to persist the selection

**Comment by mvillis** [comment]
.....really puzzled on how to best to do the ui for this one.

was thinking maybe just some check boxes on each rating for now and evolve from there.

**Comment by mvillis** [comment]
Re: UI - had an idea yesterday that we could show a floating footer once a rating is selected. It would horizontally show n buttons to select a target. Use of colour will make it easy to link the button with the full description which is visible in the main rating window. 

I think a floating footer would work on mobile as well as desktop. 

It can be optionally dismissed.

**Comment by mvillis** [comment]
What do you think @rloomans ?
https://measuremate-pr-96.herokuapp.com/

**Comment by rloomans** [comment]
Seems a little inconsistent, but it works for now... we'll test it out.

**Comment by mvillis** [comment]
the tabs on the right now update to a tick when you select both a rating and a target. subtle but I think does the job for now.
