### ISSUE TITLE
Add a assessment summary

### ISSUE THREAD

**Issue by rloomans** [mvillis/measure-mate#54]
Add a view of the assessment that just shows the current, previous and target values of the rankings (similar to the dashboard of the LAMA spreadsheet).

![image](https://cloud.githubusercontent.com/assets/92133/12159830/76396270-b531-11e5-8644-32552856c99f.png)

Maybe even a graph:

![image](https://cloud.githubusercontent.com/assets/92133/12159847/ae967766-b531-11e5-9821-409b0c3a9005.png)

**Comment by mvillis** [comment]
How you going with this one @rloomans ? Do you have some WIP somewhere?

Kinda feeling like this is the next logical card to complete.

**Comment by mvillis** [comment]
most open source reacting charting libraries seem to assume you are using Node's ecosystem.
so....looks like it'll be up to us to componentise as required. might be able to steal some of the approach from how react-chartist works: https://github.com/fraserxu/react-chartist/blob/master/index.js

still favouring chartist?

**Comment by mvillis** [comment]
Was able to build my own component around Chartist.

First simple chart:
https://measuremate-pr-98.herokuapp.com/assessment/report/1/

Still getting my head around chartist. Some simple things like adding a legend aren't that simple....

**Comment by rloomans** [comment]
Looks like a good start

**Comment by mvillis** [comment]
Merged in #110 to master. It's a good start.
Needs some refining. 
What else should we add to complete this "basic" assessment report?

**Comment by mvillis** [comment]
looks like here is some guidance on how to make your plot.ly charts more mobile friendly https://plot.ly/javascript/responsive-fluid-layout/

**Comment by rloomans** [comment]
The major thing that jumps out at me that needs to be fixed is that there are values in the yaxis layout config hard-coded only for the LAMA. Those values should come from the template's config.

``` javascript
      var layout = {
        ...,
        yaxis: {
          showgrid: true,
          tickmode: 'array',
          tickvals: [-1, 0, 1, 2, 3],
          ticktext: ['Regressive', 'N/A', 'Emerging', 'Growing', 'Sustainable'],
          range: [-1, 3],
        },
        ...
      };
```

**Comment by rloomans** [comment]
@mvillis have you looked at the latest revision of this? 

Functionally, I think we're there... At least until we have a previous measurement to do trends against. 

We still have issues with responsiveness on different devices and the colours probably need work but I think we come back to those.

**Comment by mvillis** [comment]
Was thinking of putting some badges at the top like just deployed here:
https://measuremate-pr-117.herokuapp.com/assessment/1/
(see summary tab).

the maths isn't quite right yet......

**Comment by rloomans** [comment]
Not sure I'm a fan... At least for the LAMA the target (and in the future, actions) as discussed by the team are what should be the focus for efforts.

I'll double check with others, but this may be the point where we need to add feature toggles :)

(BTW, the lack of a router in the front end is starting to get tedious :|)

**Comment by mvillis** [comment]
agree. let's kill the badges.
...and complete this card.
