### ISSUE TITLE
Add formatting for desc fields

### ISSUE THREAD

**Issue by rloomans** [mvillis/measure-mate#56]
The desc(ription) fields should allow Markdown or similar to add formatting rather than the current hack of allowing specifying a CSS class

**Comment by mvillis** [comment]
fyi - here is a tutorial form Facebook on how you can use the [marked](https://github.com/chjj/marked) library and react for formatting: https://facebook.github.io/react/docs/tutorial.html#adding-markdown

**Comment by rloomans** [comment]
There are also https://github.com/rexxars/react-markdown and https://github.com/acdlite/react-remarkable

**Comment by mvillis** [comment]
when looking at react options you often find ones that are node only (or only providing setup instructions for node). We are using bower to manage our javascript dependencies but not running with node just yet..... could move to it if it turns out to be too prohibitive.

**Comment by rloomans** [comment]
[ProseMirror](https://prosemirror.net/) looks very interesting in this space...

... and also [Draft.js](http://facebook.github.io/draft-js/docs/overview.html).
