### ISSUE TITLE
demo app not working in heroku

### ISSUE THREAD

**Issue by mvillis** [mvillis/measure-mate#6]
Currently getting an application error:

```
An error occurred in the application and your page could not be served. Please try again in a few moments.
```

**Comment by mvillis** [comment]
@mjohno @rloomans - heroku app is now working.

pass through your heroku logins and can add you.

**Comment by rloomans** [comment]
Excellent. 

My heroku login is robert@loomans.org. 

Rob

## 

Robert Loomans

**Comment by mvillis** [comment]
Rob and Matt added.

Awesome.
