### ISSUE TITLE
Hitting Next or Previous should scroll to the top

### ISSUE THREAD

**Issue by rloomans** [mvillis/measure-mate#71]
Pressing the Next or Previous button should scroll to the top.

Maybe only on mobile?

**Comment by mvillis** [comment]
the OOTB behaviour for the pager component in bootstrap seems to be for standard browsers to scroll to the top. For mobile it doesn't do anything :-(

I agree it seems to be more important for mobile than for desktop.

**Comment by mvillis** [comment]
Just implemented a pull request with some basic scroll to top behaviour.
In my testing the desktop behaviour seemed pretty ok so didn't try to distinguish between mobile and desktop.

The bigger issue is the tab fade-in / fade-out animation and the scroll to top seem to conflict with each other often causing a bit of a busy look. 
I think it could be ok but would like a second opinion @rloomans @mjohno. I've deployed the feature to prod just just go to a sample assessment like https://measuremate.herokuapp.com/assessment/55/ and try the nav.

**Comment by rloomans** [comment]
I think it’s good enough for the moment.
