### ISSUE TITLE
Add a warning for IE compatibility mode

### ISSUE THREAD

**Issue by rloomans** [mvillis/measure-mate#99]
If the user has "Display intranet sites in Compatibility View" selected then it takes precedence over the <meta> tag.

If the app finds itself running in compatibility mode, it should display a warning and explain how to disable.

Should be able to use code like that in: http://stackoverflow.com/questions/3103890/determining-why-a-page-is-being-renderred-in-compatibility-mode/29288153#29288153

**Comment by mvillis** [comment]
Was just trying the site out in IE10 Compatibility mode and it seemed to work fine. Is this consistent with your tests?

**Comment by rloomans** [comment]
It is now. Previously, if you forced on Compatibility View, the app would break... Now I can't even persuade IE 10 to turn it on.

**Comment by mvillis** [comment]
this is more consistent with what i expected.

can we close this issue? :-)

**Comment by rloomans** [comment]
I've doubled checked: I can no longer reproduce the breakage.
